apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dummy-app
  labels:
    app: {{ .Release.Name }}-dummy-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dummy-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dummy-app
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
      - name: dummy-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["sleep", "3600"]  # Simulates a long-running process
        resources:
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
            nvidia.com/gpu: {{ .Values.resources.limits.nvidia.com/gpu }}
