apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-driver-installer
  namespace: kube-system
  labels:
    app: nvidia-driver-installer
spec:
  selector:
    matchLabels:
      app: nvidia-driver-installer
  template:
    metadata:
      labels:
        app: nvidia-driver-installer
    spec:
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      containers:
      - name: nvidia-driver-installer
        image: nvidia/cuda:11.8-base-ubuntu22.04  # Change to the CUDA version you need
        securityContext:
          privileged: true  # Required for accessing /dev
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "/usr/local/cuda-11.8/bin/cuda-install-samples-11.8.sh ~ && cd ~/NVIDIA_CUDA-11.8_Samples/1_Utilities/deviceQuery && make && ./deviceQuery"]
        resources:
          requests:
            nvidia.com/gpu: 1  # Requesting GPU resources
        volumeMounts:
        - mountPath: /usr/local/nvidia
          name: nvidia
        - mountPath: /usr/local/cuda-11.8
          name: cuda
      volumes:
      - name: nvidia
        hostPath:
          path: /usr/local/nvidia
          type: DirectoryOrCreate
      - name: cuda
        hostPath:
          path: /usr/local/cuda-11.8
          type: DirectoryOrCreate
