replicaCount: 2
image:
  repository: busybox
  pullPolicy: IfNotPresent
  tag: "latest"

nodeSelector:
  usage: gpu

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
    nvidia.com/gpu: 1

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpu:
    averageUtilization: 50
